package.json

Fixes https://github.com/sourcery-ai/sourcery/issues/112

Activate Sourcery on python file open or startup finished

---

.github/workflows/publish.yml
package.json
yarn.lock

Manually triggered workflow that downloads the release from sourcery-ai/sourcery, updates the binary, pushes a new commit to master, creates a new release, and publishes the VSIX

Create publish GH action

---

package.json

Review together with https://github.com/sourcery-ai/core/pull/1433

feat: remove metrics enabled setting from json

---

walkthrough/view_welcome_file.md

This shows up in the markdown for the first step of the walkthrough.

docs: add python tag to markdown

---

package.json

The core PR - https://github.com/sourcery-ai/core/pull/1994

feat: Login from VSCode using `sourcery.login` command

---

package.json
src/extension.ts
src/hub.ts

Minor changes to the extension to enable a couple of changes to the language and hub server backends.

feat: authentication via the hub

---

src/extension.ts

feat: add Javascript and Typescript files to the document selector

---

package.json
src/extension.ts
yarn.lock

This allows us to use features from LSP version 3.17 like inlay hints

chore: Upgrade vscode-languageclient

---

media/main.js
media/vscode.css
package.json
src/extension.ts
src/rule-search.ts

feat: enable rule saving

---

.github/workflows/ci.yml
.pre-commit-config.yaml
.prettierignore
package-lock.json
package.json
src/executable.ts
src/extension.ts
src/hub.ts
src/rule-search-results.ts
src/rule-search.ts
src/uninstall.ts
yarn.lock

I just went with the prettier defaults which is a spacing of 2...

feat: add prettier for formatting

---

media/chat.css
media/vscode.css
package.json
src/chat.ts
src/extension.ts
src/recipes.ts
src/webview/chat.js
src/webview/recipes.js

- Review with https://github.com/sourcery-ai/core/pull/2723
- Make chat text area show up at the bottom of the window
- Add a recipe view to the sidebar
- Generate the buttons from a list sent from the binary
- Hook these up to send messages - at the moment they just send a basic message through the same chat API

feat: add basic recipe view and hook it up

---

media/vscode.css

fix: button margins

---

src/webview/chat.js
src/webview/recipes.js

This adds a disambiguation field to the messages and sends through the complete recipe data to allow finding by ID.

feat: allow chat to request complete recipe from the binary

---

src/chat.ts
src/extension.ts
src/recipes.ts
src/webview/chat.js
src/webview/recipes.js

feat: rework the messaging system

---

media/chat.css
src/chat.ts
src/webview/chat.js

* Converts various bits into flexboxes to correctly handle growing and shrinking
* Code blocks now overflow with an internal scrollbar rather than causing the whole section to scroll

fix: update layout and ensure code blocks do not cause the whole box to overflow

---

media/chat.css
src/chat.ts
src/extension.ts
src/webview/chat.js

* Adds a cancel button to the UI which activates the cancel command
* Updates some styles to match design doc
* Fixes some issues with spacing and layout
See backend PR https://github.com/sourcery-ai/core/pull/2794

feat: cancellation of in-progress messages #2794

---

media/chat.css
src/chat.ts
src/webview/chat.js

Review along with https://github.com/sourcery-ai/core/pull/2825

feat: Show assistant files/dirs as links

---

src/webview/chat.js

Sticky now only applies to LLM messages.

feat: scroll to bottom when new messages are sent

---

package.json
src/ask-sourcery.ts

feat: Add 'Ask Sourcery' keybinding

---

media/chat.css
src/chat.ts
src/webview/chat.js

* Make the button names a bit more generic and add a wrapper to handle them as a group
* Add a new message type to/from the script

feat: adds a button to code snippets to add them to the editor

---

media/troubleshooting.css
src/extension.ts
src/troubleshooting.ts
src/webview/troubleshooting.js
src/webview/troubleshooting.ts

**Merging to feature branch**
* Removes the issue form on submit (may change this behaviour in future)
* Handles messages from the backend by putting them in the main section
* Messages have slightly different styling depending on their type
See backend PR sourcery-ai/core#2866

feat: allow the troubleshooting to receive data back from the binary

---

media/troubleshooting.css
src/troubleshooting.ts
src/webview/troubleshooting.js
src/webview/troubleshooting.ts

**Merging to feature branch**
* adds markdown rendering and styles matching the chat
* adds sticky scrolling (copied from chat)
* adds two new action buttons: "reset" and "retry"
See sourcery-ai/core#2876

feat: markdown rendering of messages and more actions

---

media/troubleshooting.css
package.json
src/extension.ts
src/troubleshooting.ts
src/webview/troubleshooting.js
src/webview/troubleshooting.ts

* handles messages of type "input" and renders them as yes/no buttons
* also removes the retry/reset buttons from the webview itself, but adds a "Reset" at the top of the panel, like "Clear" for chat.

feat: add user input message handling

---

media/chat.css
package.json
src/chat.ts
src/code-review.ts
src/extension.ts
src/webview/chat.js
src/webview/review.js

feat: add new code review mode

---

media/troubleshooting.css
package.json
src/chat.ts
src/code-review.ts
src/extension.ts
src/troubleshooting.ts
src/webview/troubleshooting.js
src/webview/troubleshooting.ts

Adds a webview interface to the troubleshooting system.

feat: troubleshooting version 1 (frontend)

---

package.json
src/chat.ts
src/code-review.ts
src/extension.ts
src/opt-in.ts
src/recipes.ts

Review along with sourcery-ai/core#2918

feat: Add opt in webview that is shown prior to enabling the coding assistant

---

media/troubleshooting.css
src/chat.ts
src/webview/troubleshooting.js
src/webview/troubleshooting.ts

Adds support for text inputs in the troubleshooting mode and removes hard-coded start-up interface in favour of plan initialisation.
Review alongside sourcery-ai/core#2938

feat: ongoing troubleshooting chat

---

src/extension.ts

Troubleshooting excepted for now because the web app frontend hasn't been created.
See language server changes in: sourcery-ai/core#3034
**Note:** merging to feature branch.

refactor: consolidate coding assistant commands into a single one

---

src/extension.ts

feat: navigate to the correct settings section when invoked
