sourcery-ai/sourcery-vscode

- package.json
> Remove sourcery commands from command palette

- package.json
- src/extension.ts
- welcome-to-sourcery.py
Add a text with the dashboard's URL to:
* the input box for the Sourcery token (shown after the installation)
* the description of the setting Sourcery token
welcome-to-sourcery.py
* Change the link: VSCode installation instructions => Dashboard
* old docs => new docs
> Sourcery token: add links to the dashboard

- src/extension.ts
Sourcery is currently suggesting improvements on all python files, including diffs.
Amend the extension to only trigger on files on disk or newly created files.
Addresses #61
> fix: Only trigger sourcery on files that are newly created or on the file system

- src/extension.ts
Ensure that Python notebook cells in notebooks are sent through to Sourcery so that we can suggest things in them.
> fix: re-enable extension for python notebook cells

- package.json
- src/executable.ts
- src/extension.ts
Assuming core Sourcery is in the sibling folder `../core` then
`yarn run vscode_local` will start this extension with the code
checked out in core.
> chore: Add yarn run vscode_local command

- package.json
I added a stub command and forgot to remove it - at the moment it errors if you call it.
> fix: remove unimplemented command

- README.md
Address the excellent suggestions made by one of our users at https://github.com/sourcery-ai/sourcery-vscode/issues/124:
* improve explanation about our config files and link to the respective docs
* add quick links to the header of the README
* link to our docs in the  "About" section
Closes https://github.com/sourcery-ai/sourcery-vscode/issues/124.
> docs(readme): improve explanation about config files and add more links to docs

- src/extension.ts
This sets the 'owner' property on diagnostics, which should hopefully resolve https://github.com/sourcery-ai/sourcery-vscode/issues/121
There's more context in that issue.
> feat: set the diagnostic collection name in the languageclientoptions

- .github/pull_request_template.md
- package.json
- yarn.lock
> chore: Upgrade dependencies

- package.json
The current [marketplace search](https://marketplace.visualstudio.com/search?term=refactor&target=VSCode&category=Linters&sortBy=Relevance) doesn't show Sourcery in Linters for `refactor` search term.
This adds a bunch of keywords and categories.
> chore: Add categories and tags

- package.json
- src/extension.ts
* via browser
* via token
Implementation
---------------------
* `sourcery.login.choose` command
* Settings: re-activate property `sourcery.token`
* Notification `sourcery/vscode/showSettings`
> feat: VSCode login 2 ways

- .gitignore
- media/chat.css
- src/webview/chat.js
> feat: add thinking indicator to chat assistant

- media/chat.css
- src/webview/chat.js
- Put error messages in their own text bubble, and give them an error background rather than red text
- Make sure the view scrolls when messages are added
- Increase the size of the text area when you write in it
> feat: long messages should automatically scroll so the bottom

- .github/workflows/prerelease.yml
> ci: add action to publish pre-releases

- .github/workflows/prerelease.yml
> ci: fix pre-release workflow

- media/chat.css
- src/chat.ts
* Titles are smaller, bold, and have a tiny bit more space above each one 
* Lists fit inside the bubble correctly
* Only user messages are pre-wrapped - assistant messages are assumed to be markdown formatted
* Code blocks take on the color of the editor (this seems to work nicely with the highlightjs settings)
* Cancel button styles updated to work a bit better
I noticed that if you switch color themes, the code blocks continue in the old theme until the editor is restarted. I think that's alright, most people aren't deliberately switching between themes frequently, and restarting is an easy enough workaround.
> feat: improve appearance of markdown formatting

- media/chat.css
- src/chat.ts
- src/webview/chat.js
The effect is quite nice - it sticks to the bottom as expected, but you can smoothly scroll up.
> fix: scroll message window to bottom, unless the user has scrolled up

- media/chat.css
- src/chat.ts
- src/webview/chat.js
* Adds a copy button to `pre` blocks when they're rendered.
* The button only shows when you're hovering the block
> feat: add a copy button to each code block in a chat assistant message

- src/ask-sourcery.ts
- src/extension.ts
This means we can trigger chat requests from the binary and it still focuses correctly.
> feat: focus chat window on all chat requests

- package.json
- src/extension.ts
Review with https://github.com/sourcery-ai/core/pull/2831
> feat: add config and command to toggle off code lens

- media/troubleshooting.css
- package.json
- src/extension.ts
- src/troubleshooting.ts
- src/webview/troubleshooting.js
- src/webview/troubleshooting.ts
**Merging to feature branch**
* Creates a troubleshooting pane in VSCode
* The script is written in TypeScript but compiled to JavaScript, also included in the commit
* Currently just sends the submit with the prompt value
I've used the script to add a lot of the html because it means you can just reload the webview (rather than restarting the development host) when you make changes, which speeds things up a lot.
See backend PR sourcery-ai/core#2855
> feat: add troubleshooting window and connect to backend

- package.json
> fix: dev-specific local running option

- .github/workflows/publish.yml
> ci: re-add publishing to openvsx

- src/chat.ts
Use `.file()` rather than `.parse()` so that windows paths are parsed correctly. `file` doesn't seem to actually need a file specifically, a directory will do.
> fix: adjust path parsing to allow correct URI on Windows

- package.json
Make the `toggleCodeLenses` command always available - that is, stop requiring the `coding_assistant` feature flag for it to work.
> feat: make `toggleCodeLenses` always available

- welcome-to-sourcery.py
> chore: tweak welcome file to make it more immediately impactful

- src/chat.ts
* Uses URIs in place of strings, and also adds a follow-up command to correctly focus a directory in VSCode
> fix: ensure directory links work in VSCode

- src/chat.ts
- src/extension.ts
* Adds a handler for messages telling the extension to update its configuration.
Note that VSCode handles calling the language server to update configuration.
See core changes: https://github.com/sourcery-ai/core/pull/3398
See Intellij changes: https://github.com/sourcery-ai/intellij-plugin/pull/148
> feat: handle configuration changes from the app
